                 /* ******************************* */
                 /*     DCU Fuzzy Compiler          */
                 /*     Dublin City University      */
                 /* ******************************* */

#include <stdio.h>
#include <string.h>
#include "defs.h"

extern NODE *addsymb();
extern NODE *symbtab;
extern void printree();
extern void *safe_alloc();
extern void mywarn();
extern char errmsg[];
extern void petree();


/**** ROUTINES TO ADD VARIABLE AND HEDGE DEFINITONS TO THE SYMBOL TABLE ****/


PUBLIC NODE *create_var(iotype,sname,stype,smin,smax,sstep)
/* Allocate memory for a new variable, fill in its fields */
IOTYPE iotype;
char *sname;
char *stype;
float smin, smax, sstep;
{
  VAR *nvar;
	/* (1) Check the step size (to make sure map won't be too big) */
	if (((smax-smin)/sstep) > MAPSIZE) {
		sstep = (smax - smin)/MAPSIZE;
		sprintf(errmsg,"step value is too small - changing to <%.1f>",sstep);
		mywarn(errmsg);
	}
	/* (2) Allocate the memory and fill in the fields */
	nvar = (VAR *) safe_alloc(1,sizeof(VAR));
  nvar->type = stype;
  nvar->min = smin;
	nvar->max = smax;
	nvar->step = sstep;
	nvar->io = iotype;
	nvar->members = NULL;
	/* (3) Add to symbol table */
	return addsymb(&symbtab,sname,(void *)nvar,NVAR);   /* Put into symbol table */
}


PUBLIC void add_hedge(hname,hexp)
/* Add the definition of a hedge function to the symbol table */
char *hname;
NODE *hexp;
{
	addsymb(&symbtab,hname,(void *)hexp,NHED);
}




/****************** ROUTINES TO PRINT OUT THE SYMBOL TABLE *****************/

PRIVATE void printmemb(tfile,cmem)
/* Print the definition of a member function */
/* ie. either a set of points, or a function call */
FILE *tfile;
NODE *cmem;
{
	int i;
	MEMB *tmem;
	FCALL *tcall;
	if (cmem->ntype == NMEM) {    /*** Print out points ***/
		fprintf(tfile,"\n%10s:    (a member)    ",cmem->name);
		tmem = (MEMB *)cmem->contents;
		for (i=0; i<tmem->num; i++)
			fprintf(tfile,"(%.1f, %.1f) ",tmem->x[i],tmem->y[i]);
	}
	else if (cmem->ntype == NCALL) {    /*** Print out arguments ***/
		tcall = (FCALL *)cmem->contents;
		fprintf(tfile,"\n%10s:    (a f/call)    %s with (",cmem->name,tcall->fname);
		for (i=0; i<tcall->num-1; i++)
			fprintf(tfile,"%.1f ",tcall->args[i]);
		fprintf(tfile,"%.1f)",tcall->args[i]);
	}
}


PRIVATE void pfdef(tfile,fd)
/* Print a function definition */
FDEF *fd;
FILE *tfile;
{
	int i;
	for (i=0; i<fd->num; i++) {
	/* For each "line" in the definition */
		fprintf(tfile,"\n                             [From ");
		petree(tfile,fd->from[i]);
		fprintf(tfile," to ");
		petree(tfile,fd->to[i]);
		fprintf(tfile," is ");
		petree(tfile,fd->is[i]);
		fprintf(tfile,"]");
	}
}


PRIVATE void printvar(tfile,cvar)
/* Print the tree for which <cvar> is the root */
NODE *cvar;
FILE *tfile;
{
	VAR *tv;
	if (cvar->ntype == NVAR) {
		tv = (VAR *)cvar->contents;
		fprintf(tfile,"\n\n%10s:    (variable)    %s: range %.1f to %.1f step %.1f",cvar->name,tv->type,tv->min,tv->max,tv->step);
		printree(tfile,((VAR *)cvar->contents)->members,printmemb);
	}
	else if (cvar->ntype == NFUN) {
		fprintf(tfile,"\n\n%10s:    (function)    ",cvar->name);
		pfdef(tfile,(FDEF *)cvar->contents);
	}
	else if (cvar->ntype == NHED) {
		fprintf(tfile,"\n\n%10s:    (hedge fn)    ",cvar->name);
		petree(tfile,(NODE *)cvar->contents);
	}
}


PUBLIC void printall(tfile,sname)
/* Call <printree> to print out the symbol table */
FILE *tfile;
char *sname;
{
	fprintf(tfile,"/*****************************************/");
	fprintf(tfile,"\n/* Generated by DCU Fuzzy Logic Compiler */");
	fprintf(tfile,"\n/* (c) Dublin City University, 1992      */");
	if (sname[0] != '\0')
		fprintf(tfile,"\n/* Source file was:  %-12s        */",sname);
	fprintf(tfile,"\n/*****************************************/");
	fprintf(tfile,"\n\n\n             SYMBOL TABLE DUMP");
	fprintf(tfile,"\n             =================");
	fprintf(tfile,"\n\n\n-------------------------------------------------------------------------");
	fprintf(tfile,"\nName           Type          Contents    ");
	fprintf(tfile,"\n-------------------------------------------------------------------------");
	printree(tfile,symbtab,printvar);
}

